version: "3.4"
services:
  WorkingWomenApp:
    build: .
    container_name: workingwomen
    ports:
      - "80:80"
    depends_on:
      - WorkingWomenApp.Database
      - WorkingWomenApp.BLL
  WorkingWomenApp.Database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1432:1433"

    environment:
      SA_PASSWORD: "nopCommerce_db_password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

     
    restart: always

  ExampleProject:
    image: ${DOCKER_REGISTRY-}Your-app-name
    build:
      context: .
      dockerfile: app-directoty/Dockerfile
    depends_on:
    - "mssql"